---

- name: install units for ansible-pull
  become: true
  template:
    dest: /etc/systemd/system
    src: "{{ item }}"
  loop:
    - ansible-pull.service
    - ansible-pull.timer

- name: enable ansible-pull timer
  become: true
  service:
    name: ansible-pull.timer
    state: started
    enabled: yes
